builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Commit }}"
dockers:
  - image_templates:
      - "mhemeryck/modbridge:latest"
      - "mhemeryck/modbridge:{{ .Tag }}"
      - "mhemeryck/modbridge:{{ .Arch }}-{{ .Tag }}"
      - "mhemeryck/modbridge:{{ .Arch }}-latest"
      - "mhemeryck/modbridge:{{ .Arch }}"
    goarch: amd64
    goos: linux
    extra_files:
      - config.yml
